export const surpriseMePrompts = [
  "A photorealistic portrait of a young woman with flowing hair in golden sunlight, cinematic lighting, ultra-detailed skin and eyes, aesthetic composition",
  "A serene mountain lake at sunrise with mist rolling over the water, photorealistic, soft pastel colors, highly detailed reflections",
  "A futuristic city skyline at dusk with neon lights reflecting on wet streets, photorealistic, cinematic, highly detailed architecture",
  "A magical forest with glowing flowers and floating fireflies, photorealistic, soft mystical lighting, ultra-detailed textures",
  "A majestic dragon perched on a cliff with sunset in the background, photorealistic, highly detailed scales and environment",
  "A crystal-clear waterfall in a lush jungle, sunlight streaming through leaves, photorealistic, ultra-realistic water and foliage",
  "A mystical floating island above clouds with waterfalls cascading, photorealistic, cinematic lighting, hyper-detailed textures",
  "A photorealistic portrait of an elderly man with deep wrinkles and expressive eyes, soft dramatic lighting, aesthetic composition",
  "A golden hour beach scene with gentle waves and reflective wet sand, photorealistic, highly detailed textures, cinematic sky",
  "A mysterious abandoned mansion at twilight, photorealistic, soft fog and atmospheric lighting, ultra-detailed architecture",
  "A futuristic robot walking through a rainy neon street, photorealistic, reflections on wet surfaces, cinematic lighting",
  "A photorealistic forest path covered in autumn leaves, sunlight filtering through trees, ultra-detailed textures, soft cinematic mood",
  "A surreal floating crystal over a calm lake, photorealistic, soft light reflections, highly detailed and aesthetic composition",
  "A majestic eagle soaring above snow-capped mountains, photorealistic, cinematic lighting, ultra-detailed feathers and landscape",
  "A cozy, photorealistic cabin in a snowy forest at sunset, warm glowing windows, highly detailed textures and lighting",
  "A mystical cave with glowing crystals and reflective water, photorealistic, ultra-detailed, cinematic soft lighting",
  "A serene desert landscape with sand dunes and golden sunset, photorealistic, highly detailed textures, aesthetic composition",
  "A photorealistic portrait of a young man with piercing eyes and tousled hair, cinematic lighting, highly detailed skin and textures",
  "A magical night sky over mountains with glowing auroras, photorealistic, cinematic lighting, aesthetic colors",
  "A realistic city street in the rain at night, reflections on wet asphalt, neon signs, highly detailed photorealistic lighting",
  "A fantasy castle floating in clouds at sunrise, photorealistic, cinematic lighting, ultra-detailed textures",
  "A photorealistic underwater scene with colorful coral reefs and tropical fish, soft sunlight filtering through water, highly detailed",
  "A mystical forest waterfall with glowing moss and ambient light, photorealistic, aesthetic and cinematic composition",
  "A photorealistic portrait of a young woman wearing a flowing gown in a field of flowers, cinematic lighting, ultra-detailed textures",
  "A surreal landscape with giant mushrooms and mist, photorealistic, highly detailed textures, soft cinematic lighting",
  "A majestic lion resting on a rock under golden sunset, photorealistic, ultra-detailed fur and landscape, cinematic composition",
  "A serene river with cherry blossom trees reflecting on the water, photorealistic, soft sunlight, highly aesthetic composition",
  "A futuristic spaceship flying over a neon-lit city at night, photorealistic, cinematic lighting, ultra-detailed details",
  "A magical ancient library with floating books and warm lighting, photorealistic, ultra-detailed textures, aesthetic composition",
  "A photorealistic stormy ocean scene with crashing waves, dramatic lighting, ultra-detailed textures and reflections",
  "A mystical moonlit forest with fog and glowing plants, photorealistic, highly detailed and atmospheric lighting",
];